# version: '3.1'

# services:

#   wordpress:
#     image: wordpress:test49
#     restart: always
#     ports:
#       - 8081:80
#     environment:
#       WORDPRESS_DB_HOST: db
#       WORDPRESS_DB_USER: exampleuser
#       WORDPRESS_DB_PASSWORD: examplepass
#       WORDPRESS_DB_NAME: exampledb

# docker wordpress run 


#   db:
#     image: mysql:5.7
#     restart: always
#     environment:
#       MYSQL_DATABASE: exampledb
#       MYSQL_USER: exampleuser
#       MYSQL_PASSWORD: examplepass
#       MYSQL_RANDOM_ROOT_PASSWORD: '1'
#     volumes:
#       - db:/var/lib/mysql 
# volumes:
#   wordpress:
#   db:

#   docker mysql run 
